name: lokerbarufiks
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  device_info_plus: ^9.1.0
  webview_flutter: ^4.4.2

  # ✅ Firebase packages
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.3.0
  firebase_database: ^11.1.0

  # ✅ QR code
  permission_handler: ^11.3.0
  mobile_scanner: ^3.5.5

  # ✅ Plugin lainnya
  url_launcher: ^6.2.6
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
