// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuxyf8mINPaV3Kp06ffZQ06P7FRLZo4_Y',
    appId: '1:486631475172:android:ec8d364d3149b0d41ee9f1',
    messagingSenderId: '486631475172',
    projectId: 'lokerotomatis2',
    databaseURL: 'https://lokerotomatis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lokerotomatis2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOLiyz6u8xP29_XvH-GXicUAzNDETAtg',
    appId: '1:486631475172:web:b779a033a390c43d1ee9f1',
    messagingSenderId: '486631475172',
    projectId: 'lokerotomatis2',
    authDomain: 'lokerotomatis2.firebaseapp.com',
    databaseURL: 'https://lokerotomatis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lokerotomatis2.firebasestorage.app',
    measurementId: 'G-8ZWNNS8WBY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyH7B8OcbccQskNA5jjq3oCZIWEgSsEnc',
    appId: '1:486631475172:ios:24297ecc236e2b951ee9f1',
    messagingSenderId: '486631475172',
    projectId: 'lokerotomatis2',
    databaseURL: 'https://lokerotomatis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lokerotomatis2.firebasestorage.app',
    iosBundleId: 'com.example.lokerbarufiks',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyH7B8OcbccQskNA5jjq3oCZIWEgSsEnc',
    appId: '1:486631475172:ios:24297ecc236e2b951ee9f1',
    messagingSenderId: '486631475172',
    projectId: 'lokerotomatis2',
    databaseURL: 'https://lokerotomatis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lokerotomatis2.firebasestorage.app',
    iosBundleId: 'com.example.lokerbarufiks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlOLiyz6u8xP29_XvH-GXicUAzNDETAtg',
    appId: '1:486631475172:web:465769fe2b01fec01ee9f1',
    messagingSenderId: '486631475172',
    projectId: 'lokerotomatis2',
    authDomain: 'lokerotomatis2.firebaseapp.com',
    databaseURL: 'https://lokerotomatis2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lokerotomatis2.firebasestorage.app',
    measurementId: 'G-0ME6KPLDRS',
  );

}